micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/pixDB?createDatabaseIfNotExist=true
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    schema-generate: CREATE_DROP
    dialect: MARIADB

jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

itau.erp.url: http://localhost:9091

bcb.url: http://localhost:8082